[project]
name = "biograpy-server"
version = "0.1.0"
description = "MCP server for Pokemon Biographies"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.17.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
]
